name: Pull Request

on:
  pull_request:
    branches:
    - master

jobs:
  verify_labels:
    runs-on: ubuntu-latest
    name: Verify labels
    steps:
    - uses: actions/checkout@v2
    - name: Verify labels
      run: ./scripts/verify-labels.sh
      env:
        github: ${{ toJson(github) }}
  validate:
    name: Validate
    strategy:
      matrix:
        terraform: [12, 13]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      id: binaries-cache
      with:
        path: bin
        key: ${{ runner.os }}-binaries-${{ hashFiles('**/.binaries.lock') }}
        restore-keys: |
          ${{ runner.os }}-binaries-${{ hashFiles('**/.binaries.lock') }}
    - name: Get binaries
      run: ./get-binaries.sh
    - name: Validate
      run: ./scripts/tf-exec.sh validate
      env:
        TF_VERSION: ${{ matrix.terraform }}
